{
    "AssertionError": {
        "values": [
            "  File \"<string>\", line 16, in code\nAssertionError"
        ],
        "count": 2
    },
    "TimeoutException": {
        "values": [
            "  File \"<string>\", line 10, in code\n  File \"/mnt/ebs/code/forked-CodeHalu/testing_utils.py\", line 38, in timeout_handler\n    raise TimeoutException\ntesting_utils.TimeoutException",
            "  File \"<string>\", line 14, in code\n  File \"/mnt/ebs/code/forked-CodeHalu/testing_utils.py\", line 38, in timeout_handler\n    raise TimeoutException\ntesting_utils.TimeoutException"
        ],
        "count": 3
    },
    "Logic_Deviation": {
        "values": [
            "Logic_Deviation"
        ],
        "count": 2
    },
    "TypeError": {
        "values": [
            "  File \"<string>\", line 19, in code\nTypeError: 'tuple' object does not support item assignment"
        ],
        "count": 2
    },
    "Correct": {
        "values": [
            "Correct"
        ],
        "count": 1
    }
}